### ISSUE TITLE
ValueError for Precomputed

### ISSUE THREAD

**Issue by hedonistrh** [pyannote/pyannote-audio#110]
Hello Bredin,

I am trying to follow [tutorial of Speaker Change Detection](https://github.com/pyannote/pyannote-audio/tree/master/tutorials/change-detection). Firstly, I completed feature extraction part. After that, I continue with Speaker Change Detection. However, when I execute this script, I take _ValueError_. 
```
mkdir raw_scores

!pyannote-change-detection apply tutorials/change-detection/train/AMI.SpeakerDiarization.MixHeadset.train/weights/0005.pt   AMI.SpeakerDiarization.MixHeadset raw_scores

#AMI Protocol
from pyannote.database import get_protocol
protocol = get_protocol('AMI.SpeakerDiarization.MixHeadset')

# Precomputed Scores
from pyannote.audio.features import Precomputed
precomputed = Precomputed('raw_scores')

# Peak Detection
from pyannote.audio.signal import Peak
peak = Peak(alpha=0.5, min_duration=1.0, log_scale=True)

# Evaluation Metric
from pyannote.metrics.diarization import DiarizationPurityCoverageFMeasure
metric = DiarizationPurityCoverageFMeasure()

# Loop on Test Files
from pyannote.database import get_annotated
for test_file in protocol.test():

    # load reference annotation
    reference = test_file['annotation']
    uem = get_annotated(test_file)

    # load precomputed change scores as pyannote.core.SlidingWindowFeature
    scd_scores = precomputed(test_file)

    # binarize scores to obtain speech regions as pyannote.core.Timeline
    hypothesis = peak.apply(scd_scores, dimension=1)

    # evaluate speech activity detection
    metric(reference, hypothesis.to_annotation(), uem=uem)

purity, coverage, fmeasure = metric.compute_metrics()
print(f'Purity = {100*purity:.1f}% / Coverage = {100*coverage:.1f}%')
```
> ValueError                                Traceback (most recent call last)
> <ipython-input-64-1d25c1d50a7d> in <module>()
>       8 
>       9     # load precomputed change scores as pyannote.core.SlidingWindowFeature
> ---> 10     scd_scores = precomputed(test_file)
>      11 
>      12     # binarize scores to obtain speech regions as pyannote.core.Timeline
> 
> ~/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/features/utils.py in __call__(self, item)
>     277 
>     278         if self.use_memmap:
> --> 279             data = np.load(path, mmap_mode='r')
>     280         else:
>     281             data = np.load(path)
> 
> ~/anaconda3/envs/pyannote/lib/python3.6/site-packages/numpy/lib/npyio.py in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
>     414             # .npy file
>     415             if mmap_mode:
> --> 416                 return format.open_memmap(file, mode=mmap_mode)
>     417             else:
>     418                 return format.read_array(fid, allow_pickle=allow_pickle,
> 
> ~/anaconda3/envs/pyannote/lib/python3.6/site-packages/numpy/lib/format.py in open_memmap(filename, mode, dtype, shape, fortran_order, version)
>     735     """
>     736     if not isinstance(filename, basestring):
> --> 737         raise ValueError("Filename must be a string.  Memmap cannot use"
>     738                          " existing file handles.")
>     739 
> 
> ValueError: Filename must be a string.  Memmap cannot use existing file handles.

**Comment by hbredin** [comment]
Thanks. This should be fixed in latest release (1.0.1).

**Comment by hedonistrh** [comment]
I have tested it. It works now. 

_Thanks for this great library and helps. :clap:_

**Comment by bluemonk482** [comment]
Hi both, I have the latest version pyannote-audio. But I am still having the same issue, but for `speech-activity-detection`.

**Comment by hedonistrh** [comment]
There is no update after the fix. May you share your version?

**Comment by bluemonk482** [comment]
Hey @hedonistrh , I am using the latest version on Python 3.6. I am getting the same error:

```
In [10]: for test_file in protocol.test():
    ...:     reference = test_file['annotation']
    ...:     uem = get_annotated(test_file)
    ...:     sad_scores = precomputed(test_file)
    ...:     speech_regions = binarize.apply(sad_scores, dimension=1)
    ...:     metric(reference, speech_regions.to_annotation(), uem=uem)
    ...: print(f'Detection error rate = {100*abs(metric):.1f}%')
    ...:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-d8ebcc918e80> in <module>()
      2     reference = test_file['annotation']
      3     uem = get_annotated(test_file)
----> 4     sad_scores = precomputed(test_file)
      5     speech_regions = binarize.apply(sad_scores, dimension=1)
      6     metric(reference, speech_regions.to_annotation(), uem=uem)

/home/ccrmad/miniconda2/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/features/utils.py in __call__(self, item)
    277
    278         if self.use_memmap:
--> 279             data = np.load(path, mmap_mode='r')
    280         else:
    281             data = np.load(path)

/home/ccrmad/miniconda2/envs/pyannote/lib/python3.6/site-packages/numpy/lib/npyio.py in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    428             # .npy file
    429             if mmap_mode:
--> 430                 return format.open_memmap(file, mode=mmap_mode)
    431             else:
    432                 return format.read_array(fid, allow_pickle=allow_pickle,

/home/ccrmad/miniconda2/envs/pyannote/lib/python3.6/site-packages/numpy/lib/format.py in open_memmap(filename, mode, dtype, shape, fortran_order, version)
    752     """
    753     if not isinstance(filename, basestring):
--> 754         raise ValueError("Filename must be a string.  Memmap cannot use"
    755                          " existing file handles.")
    756

ValueError: Filename must be a string.  Memmap cannot use existing file handles.
```

**Comment by hedonistrh** [comment]
@bluemonk482 You use the latest version of python, however, probably you are not using the latest version of pyannote-audio library. 

May you check the output of this command in the your terminal?

`pip show pyannote.audio`

**Comment by bluemonk482** [comment]
Sorted! Apparently I have upgraded `pyannote.audio` in python3.5 not in python3.6.

 Thanks very much @hedonistrh ! Appreciate your help.
